### ISSUE TITLE
Error when installing via Homebrew on Yosemite

### ISSUE THREAD

**Issue by andyhawkes** [JohnCoates/Aerial#166]
I get an error when trying to install via Homebrew on Yosemite:

```
$ brew cask install aerial
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/aerial.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:6:in `name'
<main>:6:in `<class:Aerial>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/source/path_base.rb:65:in `eval'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/source/path_base.rb:65:in `rescue in load'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/source/path_base.rb:62:in `load'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Library/brew.rb:72:in `require?'
/usr/local/Library/brew.rb:152:in `<main>'
```

**Comment by alistairmcmillan** [comment]
Just tried here and it installed fine through cask.

You could try running the command again with `brew cask install --verbose aerial` and it might give you more information about where it's failing and maybe try running `brew doctor` and fixing any issues that brings up as well.

But I'd recommend installing the latest beta. John has fixed a number of issues and added a caching feature since the 1.1 release.

**Comment by alistairmcmillan** [comment]
No reply after eight months, closing.
